import { SchoolLayout } from '@/Components/SchoolLayout';
import { achievements, partners, programs } from '@/data/school';
import type { UnitData } from '@/types/Unit';
import { ArrowRight, Award, BriefcaseBusiness, Building2, GraduationCap, Image as ImageIcon, Palette } from 'lucide-react';

export default function SchoolIndex({ units }: { units: UnitData[] }) {
    return <SchoolLayout title="SMK Negeri 1 Bantul" description="Informasi SMK Negeri 1 Bantul: profil, program keahlian, prestasi, PPDB, BKK, karya siswa, dan Skansaba BLUD-Mart.">
        <section className="bg-primary-950 text-white">
            <div className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-14 sm:px-6 sm:py-16 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-20">
                <div>
                    <p className="mb-4 text-sm font-semibold uppercase tracking-[.14em] text-blue-200">Pendidikan Vokasi · Bantul, Yogyakarta</p>
                    <h1 className="text-4xl font-bold leading-tight tracking-tight sm:text-5xl">SMK Negeri 1 Bantul</h1>
                    <h2 className="mt-4 max-w-3xl text-2xl font-semibold leading-snug text-blue-100 sm:text-3xl">Membangun kompetensi, karakter, dan kesiapan berkarya.</h2>
                    <p className="mt-5 max-w-2xl text-base leading-7 text-blue-100">Mengembangkan keterampilan, karakter, dan kesiapan siswa menghadapi dunia kerja maupun pendidikan lanjutan.</p>
                    <div className="mt-8 flex flex-col gap-3 sm:flex-row">
                        <a href="/profil" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-white px-6 font-bold text-primary-950 hover:bg-blue-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">Jelajahi Sekolah <ArrowRight className="h-4 w-4"/></a>
                        <a href="/blud" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border border-white/40 px-6 font-bold text-white hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">Skansaba BLUD-Mart</a>
                    </div>
                    <p className="mt-6 text-sm text-blue-100">Sabdodadi, Kabupaten Bantul, Daerah Istimewa Yogyakarta</p>
                </div>
                <div className="flex min-h-64 flex-col items-center justify-center rounded-xl border border-white/25 bg-white/5 p-8 text-center sm:min-h-80">
                    <ImageIcon className="h-10 w-10 text-blue-200" aria-hidden="true"/><p className="mt-4 font-semibold">Foto sekolah atau kegiatan</p><p className="mt-1 max-w-xs text-sm leading-6 text-blue-100">Placeholder — foto resmi sekolah akan ditambahkan.</p>
                </div>
            </div>
        </section>

        <section className="py-14 sm:py-18"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8">
            <div><p className="text-sm font-bold uppercase tracking-widest text-accent-600">Profil sekolah</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Belajar kejuruan yang dekat dengan kehidupan nyata.</h2><a href="/profil" className="mt-5 inline-flex items-center gap-2 font-semibold text-primary-800">Tentang sekolah <ArrowRight className="h-4 w-4"/></a></div>
            <div className="max-w-3xl text-base leading-8 text-slate-600"><p>SMK Negeri 1 Bantul merupakan sekolah menengah kejuruan di Kabupaten Bantul, Daerah Istimewa Yogyakarta. Lingkungan belajar berfokus pada penguatan kompetensi, karakter, kreativitas, dan kesiapan siswa berkarya.</p><p className="mt-4">Melalui program keahlian dan kegiatan praktik, siswa mengembangkan bekal untuk memasuki dunia kerja, berwirausaha, atau melanjutkan pendidikan.</p></div>
        </div></section>

        <section className="bg-slate-50 py-14 sm:py-18"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-accent-600">Belajar sesuai minat</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Program Keahlian</h2><p className="mt-3 leading-7 text-slate-600">Bidang keahlian sekolah yang tercatat pada konten proyek.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{programs.map((program)=><article key={program.code} className="rounded-xl border border-slate-200 bg-white p-5"><span className="rounded-md bg-blue-50 px-2.5 py-1 text-xs font-bold text-primary-800">{program.code}</span><h3 className="mt-4 text-lg font-bold">{program.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{program.description}</p></article>)}</div><a href="/program-keahlian" className="mt-6 inline-flex items-center gap-2 font-semibold text-primary-800">Lihat program keahlian <ArrowRight className="h-4 w-4"/></a></div></section>

        <section className="py-14 sm:py-18"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-accent-600">Capaian siswa</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Prestasi</h2></div><a href="/prestasi" className="inline-flex items-center gap-2 font-semibold text-primary-800">Semua prestasi <ArrowRight className="h-4 w-4"/></a></div><div className="mt-7 grid gap-4 md:grid-cols-3">{achievements.map((item)=><article key={item.title} className="rounded-xl border border-slate-200 p-5"><Award className="h-7 w-7 text-accent-600"/><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-primary-700">{item.event}</p><h3 className="mt-2 text-lg font-bold">{item.title}</h3><p className="mt-4 border-t border-slate-100 pt-3 text-sm text-slate-600">{item.student}<span className="mt-1 block text-xs text-slate-500">{item.category} · {item.year}</span></p></article>)}</div></div></section>

        <section className="bg-primary-950 py-12 text-white"><div className="mx-auto grid max-w-7xl gap-7 px-4 sm:px-6 md:grid-cols-[.8fr_1.2fr] md:items-center lg:px-8"><div><p className="text-sm font-bold uppercase tracking-widest text-orange-300">Alumni</p><h2 className="mt-2 text-3xl font-bold">Lulusan Terbaik</h2><p className="mt-3 leading-7 text-blue-100">Cerita keberhasilan lulusan akan ditampilkan setelah data dan dokumentasi tersedia.</p></div><div className="rounded-xl border border-white/20 bg-white/5 p-6"><div className="flex items-center gap-4"><GraduationCap className="h-9 w-9 shrink-0 text-orange-300"/><div><h3 className="font-bold">Profil lulusan segera hadir</h3><p className="mt-1 text-sm text-blue-100">Placeholder — belum ada data lulusan terbaik yang terverifikasi.</p></div></div></div></div></section>

        <section className="py-14 sm:py-18"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-accent-600">Kolaborasi</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Kerja Sama Industri</h2><p className="mt-3 leading-7 text-slate-600">Nama mitra yang tercatat pada konten proyek. Logo mitra belum tersedia.</p></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{partners.map((partner)=><div key={partner.name} className="flex min-h-20 flex-col justify-center rounded-lg border border-slate-200 px-4 py-3"><strong className="text-sm text-slate-800">{partner.name}</strong><span className="mt-1 text-xs text-slate-500">{partner.field}</span></div>)}</div></div></section>

        <section className="bg-slate-50 py-14 sm:py-18"><div className="mx-auto grid max-w-7xl gap-4 px-4 sm:px-6 md:grid-cols-2 lg:px-8">
            <a href="/ppdb" className="rounded-xl border border-orange-200 bg-white p-6 hover:shadow-md"><GraduationCap className="h-7 w-7 text-accent-600"/><h2 className="mt-4 text-2xl font-bold">PPDB</h2><p className="mt-2 text-sm leading-6 text-slate-600">Akses informasi penerimaan peserta didik baru.</p><span className="mt-4 inline-flex items-center gap-2 font-semibold text-primary-800">Informasi PPDB <ArrowRight className="h-4 w-4"/></span></a>
            <a href="/bkk" className="rounded-xl border border-slate-200 bg-white p-6 hover:shadow-md"><BriefcaseBusiness className="h-7 w-7 text-primary-700"/><h2 className="mt-4 text-2xl font-bold">PKL & Career Center</h2><p className="mt-2 text-sm leading-6 text-slate-600">Informasi PKL, BKK, dan kesiapan memasuki dunia kerja.</p><span className="mt-4 inline-flex items-center gap-2 font-semibold text-primary-800">Selengkapnya <ArrowRight className="h-4 w-4"/></span></a>
        </div></section>

        <section className="py-14 sm:py-18"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-accent-600">Kabar sekolah</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Berita & Informasi</h2></div><a href="/informasi" className="inline-flex items-center gap-2 font-semibold text-primary-800">Semua informasi <ArrowRight className="h-4 w-4"/></a></div><div className="mt-7 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="overflow-hidden rounded-xl border border-slate-200"><div className="flex min-h-40 items-center justify-center bg-slate-100 text-center text-sm text-slate-500"><div><ImageIcon className="mx-auto h-8 w-8"/><p className="mt-2">Foto artikel akan ditambahkan</p></div></div><div className="p-5"><p className="text-xs font-bold uppercase text-accent-600">Placeholder · berita utama</p><h3 className="mt-2 text-lg font-bold">Berita sekolah akan ditampilkan di sini</h3><p className="mt-1 text-sm text-slate-600">Konten publikasi dan tanggal akan diisi setelah data tersedia.</p></div></article><div className="grid gap-3">{['Informasi kegiatan sekolah','Pengumuman sekolah','Cerita pembelajaran siswa'].map(title=><article key={title} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase text-accent-600">Placeholder · informasi</p><h3 className="mt-2 font-bold">{title}</h3><p className="mt-1 text-sm text-slate-500">Konten akan diperbarui setelah data tersedia.</p></article>)}</div></div></div></section>

        <section className="bg-slate-50 py-14 sm:py-18"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-accent-600">Unit Produksi sekolah</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Produk Unggulan Sekolah</h2><p className="mt-3 max-w-2xl text-slate-600">Kenali Unit Produksi melalui portal pusat Skansaba BLUD-Mart.</p></div><a href="/blud/units" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-primary-800 px-5 font-bold text-white hover:bg-primary-900">Jelajahi Semua Unit <ArrowRight className="h-4 w-4"/></a></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{units.slice(0,3).map(unit=><article key={unit.id} className="flex items-start gap-4 rounded-xl border border-slate-200 bg-white p-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-blue-50 text-primary-700">{unit.logo?<img src={`/storage/${unit.logo}`} alt={`Logo ${unit.name}`} loading="lazy" className="h-full w-full object-contain p-1"/>:<Building2 aria-hidden="true"/>}</span><span><strong className="block">{unit.name}</strong><small className="text-slate-500">{unit.category}</small><small className="mt-1 block text-xs leading-5 text-slate-500">{unit.description ?? 'Informasi unit akan diperbarui.'}</small></span></article>)}</div></div></section>

        <section className="py-14"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-5 rounded-xl bg-primary-950 p-7 text-white sm:grid-cols-[1fr_auto] sm:items-center sm:p-9"><div><h2 className="text-2xl font-bold">Karya Siswa</h2><p className="mt-2 text-sm leading-6 text-blue-100">Ruang apresiasi untuk karya yang lahir dari proses belajar.</p></div><a href="/karya-siswa" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-white px-5 font-semibold text-primary-950">Lihat Karya Siswa <Palette className="h-4 w-4"/></a></div></div></section>
    </SchoolLayout>;
}
