import { PublicLayout } from '@/Components/PublicLayout';
import { UnitCard } from '@/Components/UnitCard';
import { Button } from '@/Components/ui/button';
import type { UnitData } from '@/types/Unit';
import { ArrowRight, Building2, GraduationCap, Network } from 'lucide-react';

export default function BludIndex({ units }: { units: UnitData[] }) {
    return <PublicLayout title="Skansaba BLUD-Mart" description="Portal digital pusat Unit Produksi SMKN 1 Bantul. Jelajahi direktori unit dan lanjutkan ke website eksternal bila tersedia.">
        <section className="bg-primary-950 text-white"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-24 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-300">Digital Ecosystem SMKN 1 Bantul</p><h1 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">SKANSABA BLUD-MART</h1><p className="mt-4 text-xl font-medium text-blue-100">Portal Digital Unit Produksi SMKN 1 Bantul</p><p className="mt-5 max-w-2xl leading-7 text-blue-100">Satu pintu informasi untuk mengenal Unit Produksi sekolah dan mengakses website masing-masing unit ketika sudah tersedia.</p><div className="mt-8"><a href="/blud/units"><Button size="lg" className="gap-2 bg-accent-500 text-white hover:bg-accent-600">Jelajahi Semua Unit <ArrowRight className="h-4 w-4"/></Button></a></div></div></section>
        <section className="py-14 sm:py-18"><div className="mx-auto grid max-w-7xl gap-5 px-4 sm:px-6 md:grid-cols-3 lg:px-8">{[[Network,'Terhubung dalam satu portal','Informasi dasar unit dihimpun di satu direktori pusat.'],[GraduationCap,'Belajar lewat praktik','Unit Produksi mendukung pengalaman belajar vokasi dan karya siswa.'],[Building2,'Website unit terpisah','Tautan mengarah ke website eksternal yang dikelola masing-masing pihak.']].map(([Icon,title,copy])=>{const IconComponent=Icon as typeof Network;return <article key={title as string} className="rounded-2xl border border-slate-200 bg-white p-6"><IconComponent className="h-7 w-7 text-primary-700"/><h2 className="mt-4 font-bold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{copy as string}</p></article>;})}</div></section>
        <section className="bg-slate-50 py-14 sm:py-18"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-accent-600">Direktori pusat</p><h2 className="mt-2 text-3xl font-bold">Unit Produksi</h2><p className="mt-2 text-slate-600">Informasi singkat unit dan tautan menuju website eksternal masing-masing.</p></div><a href="/blud/units" className="inline-flex items-center gap-2 font-bold text-primary-800">Lihat semua unit <ArrowRight className="h-4 w-4"/></a></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{units.slice(0,6).map(unit=><UnitCard key={unit.id} unit={unit}/>)}</div></div></section>
        <section className="py-14"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-5 rounded-2xl bg-orange-50 p-7 sm:flex-row sm:items-center sm:p-9"><div><h2 className="text-2xl font-bold">Karya siswa</h2><p className="mt-2 text-slate-600">Kenali ruang kreativitas dan pembelajaran berbasis karya di sekolah.</p></div><a href="/karya-siswa"><Button variant="outline" className="gap-2">Lihat Karya Siswa <ArrowRight className="h-4 w-4"/></Button></a></div></section>
    </PublicLayout>;
}
